const USER_ALREADY_EXISTS_USE_ANOTHER_EMAIL =
  "USER_ALREADY_EXISTS_USE_ANOTHER_EMAIL";
const USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS";

export { USER_ALREADY_EXISTS_USE_ANOTHER_EMAIL, USER_ALREADY_EXISTS };
