export const AUTH_ERRORS = {
  USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
  INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  SESSION_EXPIRED: "AUTH_SESSION_EXPIRED",
  FORBIDDEN: "AUTH_FORBIDDEN",
  EMAIL_NOT_VERIFIED: "AUTH_EMAIL_NOT_VERIFIED",
  ACCOUNT_LOCKED: "AUTH_ACCOUNT_LOCKED",
} as const;

export const QUIZ_ERRORS = {
  QUIZ_NOT_FOUND: "QUIZ_NOT_FOUND",
  QUIZ_CLOSED: "QUIZ_CLOSED",
  QUIZ_ALREADY_ATTEMPTED: "QUIZ_ALREADY_ATTEMPTED",
  QUIZ_NOT_STARTED: "QUIZ_NOT_STARTED",
  QUESTION_NOT_FOUND: "QUESTION_NOT_FOUND",
  INVALID_ANSWER_FORMAT: "INVALID_ANSWER_FORMAT",
  ATTEMPT_CREATION_FAILED: "ATTEMPT_CREATION_FAILED",
  QUIZ_DATA_FETCH_FAILED: "QUIZ_DATA_FETCH_FAILED",
  QUIZ_JOIN_FAILED: "QUIZ_JOIN_FAILED",
} as const;

export const SERVER_ERRORS = {
  DATABASE_ERROR: "SERVER_DATABASE_ERROR",
  INTERNAL_ERROR: "SERVER_INTERNAL_ERROR",
  TRANSACTION_FAILED: "SERVER_TRANSACTION_FAILED",
  SERVICE_UNAVAILABLE: "SERVER_SERVICE_UNAVAILABLE",
} as const;

export const CLIENT_ERRORS = {
  NETWORK_ERROR: "CLIENT_NETWORK_ERROR",
  BAD_REQUEST: "CLIENT_BAD_REQUEST",
  UNAUTHORIZED: "CLIENT_UNAUTHORIZED",
  FORBIDDEN: "CLIENT_FORBIDDEN",
  NOT_FOUND: "CLIENT_NOT_FOUND",
  VALIDATION_ERROR: "CLIENT_VALIDATION_ERROR",
} as const;

export const GLOBAL_ERRORS = {
  SOMETHING_WENT_WRONG: "GLOBAL_SOMETHING_WENT_WRONG",
  INVALID_INPUT: "GLOBAL_INVALID_INPUT",
  RESOURCE_NOT_FOUND: "GLOBAL_RESOURCE_NOT_FOUND",
  UNKNOWN_ERROR: "GLOBAL_UNKNOWN_ERROR",
} as const;

// Optional: export a single bundle if you prefer
export const ERRORS = {
  ...AUTH_ERRORS,
  ...QUIZ_ERRORS,
  ...SERVER_ERRORS,
  ...CLIENT_ERRORS,
  ...GLOBAL_ERRORS,
} as const;

export type ErrorCode = keyof typeof ERRORS;
